### ISSUE TITLE
Parsing package.json error - crashing in production Electron 11 app

### ISSUE THREAD

**Issue by andrewschreiber** [sindresorhus/active-win#102]
Active-win works delightfully while building in development. Great package! However in a production build I get this error.

![image](https://user-images.githubusercontent.com/1892071/111121223-9c750480-8529-11eb-96d8-c5457daa7b4f.png)

FWIW I yarn added the package into my src (aka app) directory, because when installing to the root directory I get this error.

![image](https://user-images.githubusercontent.com/1892071/111121428-dcd48280-8529-11eb-822d-f16395faf72e.png)

I sanity checked `package.json` in active-win and it seems properly constructed.

**Comment by andrewschreiber** [comment]
Running `yarn add active-win` within my src (aka app) directory throws this error, but interestingly the library can be successfully imported and used in development mode. Only once a production build is made does it fail. However it does corrupt all future yarn calls.
```shell
~/git/focusbase/src(as-mvp-ui-updates ✔) yarn add active-win
yarn add v1.22.10
warning package.json: No license field
warning focusbase@0.1.7: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
warning focusbase@0.1.7: No license field
success Saved 12 new dependencies.
info Direct dependencies
└─ active-win@6.3.0
info All dependencies
├─ active-win@6.3.0
├─ ffi-napi@2.5.0
├─ get-symbol-from-current-process-h@1.0.2
├─ get-uv-event-loop-napi-h@1.0.6
├─ iconv@2.3.5
├─ ms@2.1.3
├─ nan@2.14.2
├─ ref-napi@1.5.2
├─ ref-struct-di@1.1.1
├─ ref-struct-napi@1.1.1
├─ ref-wchar-napi@1.0.3
└─ safer-buffer@2.1.2
$ yarn electron-rebuild
yarn run v1.22.10
warning package.json: No license field
$ node -r ../.erb/scripts/BabelRegister.js ../.erb/scripts/ElectronRebuild.js
⠸ Building modules: 0/6gyp info find Python using Python version 3.9.1 found at "/usr/local/opt/python@3.9/bin/python3.9"
gyp info find Python using Python version 3.9.1 found at "/usr/local/opt/python@3.9/bin/python3.9"
⠼ Building modules: 0/6gyp info find Python using Python version 3.9.1 found at "/usr/local/opt/python@3.9/bin/python3.9"
gyp info find Python using Python version 3.9.1 found at "/usr/local/opt/python@3.9/bin/python3.9"
gyp http GET https://www.electronjs.org/headers/v11.0.1/node-v11.0.1-headers.tar.gz
gyp info find Python using Python version 3.9.1 found at "/usr/local/opt/python@3.9/bin/python3.9"
gyp info find Python using Python version 3.9.1 found at "/usr/local/opt/python@3.9/bin/python3.9"
gyp http GET https://www.electronjs.org/headers/v11.0.1/node-v11.0.1-headers.tar.gz
gyp http GET https://www.electronjs.org/headers/v11.0.1/node-v11.0.1-headers.tar.gz
gyp http GET https://www.electronjs.org/headers/v11.0.1/node-v11.0.1-headers.tar.gz
gyp http GET https://www.electronjs.org/headers/v11.0.1/node-v11.0.1-headers.tar.gz
gyp http GET https://www.electronjs.org/headers/v11.0.1/node-v11.0.1-headers.tar.gz
⠼ Building modules: 0/6gyp http 200 https://www.electronjs.org/headers/v11.0.1/node-v11.0.1-headers.tar.gz
gyp http 200 https://www.electronjs.org/headers/v11.0.1/node-v11.0.1-headers.tar.gz
gyp http 200 https://www.electronjs.org/headers/v11.0.1/node-v11.0.1-headers.tar.gz
gyp http 200 https://www.electronjs.org/headers/v11.0.1/node-v11.0.1-headers.tar.gz
gyp http 200 https://www.electronjs.org/headers/v11.0.1/node-v11.0.1-headers.tar.gz
gyp http 200 https://www.electronjs.org/headers/v11.0.1/node-v11.0.1-headers.tar.gz
⠇ Building modules: 0/6gyp http GET https://www.electronjs.org/headers/v11.0.1/SHASUMS256.txt
gyp http GET https://www.electronjs.org/headers/v11.0.1/SHASUMS256.txt
gyp http GET https://www.electronjs.org/headers/v11.0.1/SHASUMS256.txt
gyp http GET https://www.electronjs.org/headers/v11.0.1/SHASUMS256.txt
gyp http GET https://www.electronjs.org/headers/v11.0.1/SHASUMS256.txt
⠏ Building modules: 0/6gyp http GET https://www.electronjs.org/headers/v11.0.1/SHASUMS256.txt
⠧ Building modules: 0/6gyp http 200 https://www.electronjs.org/headers/v11.0.1/SHASUMS256.txt
gyp http 200 https://www.electronjs.org/headers/v11.0.1/SHASUMS256.txt
gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
gyp info spawn args [
gyp info spawn args   '/Users/andrewschreiber/git/focusbase/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/focusbase/src/node_modules/ref-wchar-napi/node_modules/ref-napi/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/focusbase/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/focusbase/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/andrewschreiber/git/focusbase/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/andrewschreiber/git/focusbase/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/andrewschreiber/git/focusbase/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/andrewschreiber/git/focusbase/src/node_modules/ref-wchar-napi/node_modules/ref-napi',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp http 200 https://www.electronjs.org/headers/v11.0.1/SHASUMS256.txt
gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
gyp info spawn args [
gyp info spawn args   '/Users/andrewschreiber/git/focusbase/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/focusbase/src/node_modules/ref-wchar-napi/node_modules/ref-napi/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/focusbase/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/focusbase/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/andrewschreiber/git/focusbase/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/andrewschreiber/git/focusbase/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/andrewschreiber/git/focusbase/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/andrewschreiber/git/focusbase/src/node_modules/ref-wchar-napi/node_modules/ref-napi',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
gyp info spawn args [
gyp info spawn args   '/Users/andrewschreiber/git/focusbase/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/focusbase/src/node_modules/ref-wchar-napi/node_modules/ref-napi/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/focusbase/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/focusbase/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/andrewschreiber/git/focusbase/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/andrewschreiber/git/focusbase/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/andrewschreiber/git/focusbase/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/andrewschreiber/git/focusbase/src/node_modules/ref-wchar-napi/node_modules/ref-napi',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp http 200 https://www.electronjs.org/headers/v11.0.1/SHASUMS256.txt
gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
gyp info spawn args [
gyp info spawn args   '/Users/andrewschreiber/git/focusbase/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/focusbase/src/node_modules/ref-wchar-napi/node_modules/ref-napi/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/focusbase/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/focusbase/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/andrewschreiber/git/focusbase/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/andrewschreiber/git/focusbase/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/andrewschreiber/git/focusbase/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/andrewschreiber/git/focusbase/src/node_modules/ref-wchar-napi/node_modules/ref-napi',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp http 200 https://www.electronjs.org/headers/v11.0.1/SHASUMS256.txt
gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
gyp info spawn args [
gyp info spawn args   '/Users/andrewschreiber/git/focusbase/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/focusbase/src/node_modules/ref-wchar-napi/node_modules/ref-napi/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/focusbase/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/focusbase/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/andrewschreiber/git/focusbase/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/andrewschreiber/git/focusbase/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/andrewschreiber/git/focusbase/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/andrewschreiber/git/focusbase/src/node_modules/ref-wchar-napi/node_modules/ref-napi',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
⠇ Building modules: 0/6gyp http 200 https://www.electronjs.org/headers/v11.0.1/SHASUMS256.txt
gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
gyp info spawn args [
gyp info spawn args   '/Users/andrewschreiber/git/focusbase/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/focusbase/src/node_modules/ref-wchar-napi/node_modules/ref-napi/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/focusbase/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrewschreiber/git/focusbase/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/andrewschreiber/git/focusbase/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/andrewschreiber/git/focusbase/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/andrewschreiber/git/focusbase/src/node_modules/ref-wchar-napi/node_modules/ref-napi/11.0.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/andrewschreiber/git/focusbase/src/node_modules/ref-wchar-napi/node_modules/ref-napi',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
⠧ Building modules: 0/6gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/nothing/../../../node-addon-api/src/nothing.o
  CC(target) Release/obj.target/nothing/../../../node-addon-api/src/nothing.o
  CC(target) Release/obj.target/nothing/../../../node-addon-api/src/nothing.o
  CC(target) Release/obj.target/nothing/../../../node-addon-api/src/nothing.o
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
⠇ Building modules: 0/6  CC(target) Release/obj.target/nothing/../../../node-addon-api/src/nothing.o
  CC(target) Release/obj.target/nothing/../../../node-addon-api/src/nothing.o
rm: ./Release/.deps/Release/obj.target/nothing/../../../node-addon-api/src/nothing.o.d.raw: No such file or directory
make: *** [Release/obj.target/nothing/../../../node-addon-api/src/nothing.o] Error 1
sed: ./Release/.deps/Release/obj.target/nothing/../../../node-addon-api/src/nothing.o.d.raw: No such file or directory
./Release/.deps/Release/obj.target/nothing/../../../node-addon-api/src/nothing.o.d.raw: No such file or directory
make: *** [Release/obj.target/nothing/../../../node-addon-api/src/nothing.o] Error 1
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/Users/andrewschreiber/git/focusbase/src/node_modules/electron-active-window'.
Error: `make` failed with exit code: 2



Error: node-gyp failed to rebuild '/Users/andrewschreiber/git/focusbase/src/node_modules/electron-active-window'.
Error: `make` failed with exit code: 2


    at ModuleRebuilder.rebuildNodeGypModule (/Users/andrewschreiber/git/focusbase/node_modules/electron-rebuild/lib/src/module-rebuilder.js:193:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Rebuilder.rebuildModuleAt (/Users/andrewschreiber/git/focusbase/node_modules/electron-rebuild/lib/src/rebuild.js:183:9)
    at async Promise.all (index 5)
    at async Rebuilder.rebuild (/Users/andrewschreiber/git/focusbase/node_modules/electron-rebuild/lib/src/rebuild.js:141:13)
    at async /Users/andrewschreiber/git/focusbase/node_modules/electron-rebuild/lib/src/cli.js:145:9
  LIBTOOL-STATIC Release/nothing.a
  LIBTOOL-STATIC Release/nothing.a
sed: ./Release/.deps/Release/obj.target/nothing/../../../node-addon-api/src/nothing.o.d.raw: No such file or directory
sed: ./Release/.deps/Release/obj.target/nothing/../../../node-addon-api/src/nothing.o.d.raw: No such file or directory
make: *** [Release/obj.target/nothing/../../../node-addon-api/src/nothing.o] Error 1
make: *** [Release/obj.target/nothing/../../../node-addon-api/src/nothing.o] Error 1
child_process.js:655
    throw err;
    ^

Error: Command failed: ../node_modules/.bin/electron-rebuild --parallel --force --types prod,dev,optional --module-dir .
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at Object.<anonymous> (/Users/andrewschreiber/git/focusbase/.erb/scripts/ElectronRebuild.js:18:3)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Module._compile (/Users/andrewschreiber/git/focusbase/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.newLoader [as .js] (/Users/andrewschreiber/git/focusbase/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  status: 255,
  signal: null,
  output: [ null, null, null ],
  pid: 37890,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
~/git/focusbase/src(as-mvp-ui-updates ✗) warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
  CXX(target) Release/obj.target/binding/src/binding.o
  CXX(target) Release/obj.target/binding/src/binding.o
../src/binding.cc:305:13: warning: moving a temporary ../src/binding.ccobject: 305prevents: 13copy:  elision [-Wpessimizing-move]warning:
moving a temporary object prevents copy elision [-Wpessimizing-move]
    *rptr = std::move(Reference<Object>::New(val));
            ^
    *rptr = std::move(Reference<Object>::New(val));
            ^
../src/binding.cc:305:../src/binding.cc13::305 :13:note : removenote : std::move removecall  std::movehere call
 here
    *rptr = std::move(Reference<Object>::New(val));
    *rptr = std::move(Reference<Object>::New(val));
            ^~~~~~~~~~                           ~
            ^~~~~~~~~~                           ~
1 warning generated.
1 warning generated.
sed: ./Release/.deps/Release/obj.target/binding/src/binding.o.d.raw: No such file or directory
  SOLINK_MODULE(target) Release/binding.node
rm: ./Release/.deps/Release/obj.target/binding/src/binding.o.d.raw: No such file or directory
make: *** [Release/obj.target/binding/src/binding.o] Error 1
```

**Comment by andrewschreiber** [comment]
This issue also happens with the default project from https://github.com/electron-react-boilerplate/electron-react-boilerplate

**Comment by andrewschreiber** [comment]
Confirmed this issue happens `electron-react-boilerplate` with multiple node versions on multiple computers (one Catalina, one BigSur). However it does not happen on the Electron quick start project https://www.electronjs.org/docs/tutorial/quick-start, which suggests its an issue with the boilerplate. Creating an issue there.
