### ISSUE TITLE
Getting  UNCAUGHT EXCEPTION while doing npm run build:windows

### ISSUE THREAD

**Issue by HARJEETSINGHX** [sindresorhus/active-win#176]
**I have cloned the repo and am doing npm: run build: windows getting following error.**

Please let me know what am doing wrong.

`node-pre-gyp ERR! UNCAUGHT EXCEPTION
node-pre-gyp ERR! stack Error: ENOENT: no such file or directory, rename 'build-tmp-napi-v3' -> 'build'
node-pre-gyp ERR! stack     at Object.renameSync (fs.js:756:3)
node-pre-gyp ERR! stack     at Object.module.exports.swap_build_dir_in (C:\Users\91956\AppData\Roaming\nvm\v14.0.0\node_modules\node-pre-gyp\lib\util\napi.js:179:6)
node-pre-gyp ERR! stack     at C:\Users\91956\AppData\Roaming\nvm\v14.0.0\node_modules\node-pre-gyp\lib\build.js:21:18
node-pre-gyp ERR! stack     at handle_gyp_opts (C:\Users\91956\AppData\Roaming\nvm\v14.0.0\node_modules\node-pre-gyp\lib\util\handle_gyp_opts.js:102:12)
node-pre-gyp ERR! stack     at do_build (C:\Users\91956\AppData\Roaming\nvm\v14.0.0\node_modules\node-pre-gyp\lib\build.js:13:5)
node-pre-gyp ERR! stack     at build (C:\Users\91956\AppData\Roaming\nvm\v14.0.0\node_modules\node-pre-gyp\lib\build.js:49:16)
node-pre-gyp ERR! stack     at Object.self.commands.<computed> [as build] (C:\Users\91956\AppData\Roaming\nvm\v14.0.0\node_modules\node-pre-gyp\lib\node-pre-gyp.js:52:37)
node-pre-gyp ERR! stack     at run (C:\Users\91956\AppData\Roaming\nvm\v14.0.0\node_modules\node-pre-gyp\bin\node-pre-gyp:82:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (C:\Users\91956\AppData\Roaming\nvm\v14.0.0\node_modules\node-pre-gyp\bin\node-pre-gyp:134:1)
node-pre-gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:1185:30)
node-pre-gyp ERR! System Windows_NT 10.0.22000
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "build" "--debug"
node-pre-gyp ERR! cwd C:\Users\91956\active-win`

<img width="675" alt="Screenshot 2024-02-20 224638" src="https://github.com/sindresorhus/active-win/assets/159790639/383450ca-64ef-4467-a9a5-9403b6efcfe9">

**Comment by Nantris** [comment]
It builds for me. What version of Windows? Are you running `cmd` as administrator? You probably shouldn't be doing that, though I don't know it's necessarily the cause of your problem.,
