### ISSUE TITLE
Error: Cannot find module 'ffi'

### ISSUE THREAD

**Issue by AukeTembrink** [sindresorhus/active-win#25]
I have installed active-win via `npm install --save active-win` and I am receiving the following error on a fresh nodeJS project as soon as I run the Usage Example.

OS: Windows 10
NodeJS: v8.9.0

```Error: Cannot find module 'ffi'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (c:\Users\me\Desktop\TMP\active-win\node_modules\active-win\lib\windows.js:4:13)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)```

**Comment by sindresorhus** [comment]
That mean `ffi` failed to install. Look over the terminal output from installing this module.

**Comment by AukeTembrink** [comment]
I found out that node seems to ignore my %PYTHON% environment variable when trying to install ffi.
