### ISSUE TITLE
Console log when getting mac window fails

### ISSUE THREAD

**Issue by thomsa-swi** [sindresorhus/active-win#37]
Hey!

I'm constantly having errors thrown when running on mac, which by default is not a problem, but there's a console log which pollutes my running process.
Can it be removed? If someone wants to have the error printed out they can do manually by catching the error. Actually this would mean that the try-catch block is not necessary (since currently it's there only to write the error to the console)

https://github.com/sindresorhus/active-win/blob/b8573b9059a534ed0d948deff486df8de58b54d2/lib/macos.js#L13

**Comment by sindresorhus** [comment]
Can you share the error? Would be good to get that fixed.

**Comment by matthewjumpsoffbuildings** [comment]
i believe this is the same issue as #32 

the error is something like this
```
Error: Error parsing window data
    at parseMac (/Users/matt/Dev/time-tracker/node_modules/active-win/lib/macos.js:14:9)
    at AsyncFunction.module.exports.sync (/Users/matt/Dev/time-tracker/node_modules/active-win/lib/macos.js:23:29)
    at Function.module.exports.sync (/Users/matt/Dev/time-tracker/node_modules/active-win/index.js:21:33)
    at Timeout.monitorCallback [as _onTimeout] (/Users/matt/Dev/time-tracker/index.js:214:28)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseMac (/Users/matt/Dev/time-tracker/node_modules/active-win/lib/macos.js:11:15)
    at AsyncFunction.module.exports.sync (/Users/matt/Dev/time-tracker/node_modules/active-win/lib/macos.js:23:29)
    at Function.module.exports.sync (/Users/matt/Dev/time-tracker/node_modules/active-win/index.js:21:33)
    at Timeout.monitorCallback [as _onTimeout] (/Users/matt/Dev/time-tracker/index.js:214:28)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
active-window failed:
 Error: Error parsing window data
    at parseMac (/Users/matt/Dev/time-tracker/node_modules/active-win/lib/macos.js:14:9)
    at AsyncFunction.module.exports.sync (/Users/matt/Dev/time-tracker/node_modules/active-win/lib/macos.js:23:29)
    at Function.module.exports.sync (/Users/matt/Dev/time-tracker/node_modules/active-win/index.js:21:33)
    at Timeout.monitorCallback [as _onTimeout] (/Users/matt/Dev/time-tracker/index.js:214:28)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
```

**Comment by sindresorhus** [comment]
Fixed in v5.
