### ISSUE TITLE
Cannot install module

### ISSUE THREAD

**Issue by PragmaticEd** [sindresorhus/active-win#38]
```
>> npm install active-win

> iconv@2.3.2 install C:\Users\PragmaticEd\workspace\_private\clipboard-manager\node_modules\iconv
> node-gyp rebuild


C:\Users\PragmaticEd\workspace\_private\clipboard-manager\node_modules\iconv>if not defined npm_config_node_gyp (node "C:\develop\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\develop\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: D:\develop\Python3.7.2\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\develop\\nodejs\\node.exe" "C:\\develop\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\PragmaticEd\workspace\_private\clipboard-manager\node_modules\iconv
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

> ref-napi@1.4.1 install C:\Users\PragmaticEd\workspace\_private\clipboard-manager\node_modules\ref-napi
> node-gyp rebuild
```

```
>> python --version
Python 3.7.2
>> npm -v
6.4.1
>> node -v
v10.15.0
```

Windows 10 1809 b17763.316 Pro Official

**Comment by sindresorhus** [comment]
The error is coming from a dependency, not this project. Try to do some Googling.
