### ISSUE TITLE
Unable to install as npm package

### ISSUE THREAD

**Issue by vickylance** [sindresorhus/active-win#43]
I am trying to do a npm install of this package and I am getting this error.

```
E:\Projects\JS\Electron\macro-recorder>npm install active-win

> iconv@2.3.3 install E:\Projects\JS\Electron\macro-recorder\node_modules\iconv
> node-gyp rebuild


E:\Projects\JS\Electron\macro-recorder\node_modules\iconv>if not defined npm_config_node_gyp (node "C:\Users\vkkpp\AppData\Local\nvs\node\8.14.0\x64\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\vkkpp\AppData\Local\nvs\node\8.14.0\x64\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB4025: The project file could not be loaded. Root element is missing.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\vkkpp\AppData\Local\nvs\node\8.14.0\x64\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\vkkpp\\AppData\\Local\\nvs\\node\\8.14.0\\x64\\node.exe" "C:\\Users\\vkkpp\\AppData\\Local\\nvs\\node\\8.14.0\\x64\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\Projects\JS\Electron\macro-recorder\node_modules\iconv
gyp ERR! node -v v8.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

> ref-napi@1.4.1 install E:\Projects\JS\Electron\macro-recorder\node_modules\ref-napi
> node-gyp rebuild


E:\Projects\JS\Electron\macro-recorder\node_modules\ref-napi>if not defined npm_config_node_gyp (node "C:\Users\vkkpp\AppData\Local\nvs\node\8.14.0\x64\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\vkkpp\AppData\Local\nvs\node\8.14.0\x64\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB4025: The project file could not be loaded. Root element is missing.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\vkkpp\AppData\Local\nvs\node\8.14.0\x64\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\vkkpp\\AppData\\Local\\nvs\\node\\8.14.0\\x64\\node.exe" "C:\\Users\\vkkpp\\AppData\\Local\\nvs\\node\\8.14.0\\x64\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\Projects\JS\Electron\macro-recorder\node_modules\ref-napi
gyp ERR! node -v v8.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

> ref@1.3.5 install E:\Projects\JS\Electron\macro-recorder\node_modules\ref
> node-gyp rebuild


E:\Projects\JS\Electron\macro-recorder\node_modules\ref>if not defined npm_config_node_gyp (node "C:\Users\vkkpp\AppData\Local\nvs\node\8.14.0\x64\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\vkkpp\AppData\Local\nvs\node\8.14.0\x64\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB4025: The project file could not be loaded. Root element is missing.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\vkkpp\AppData\Local\nvs\node\8.14.0\x64\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\vkkpp\\AppData\\Local\\nvs\\node\\8.14.0\\x64\\node.exe" "C:\\Users\\vkkpp\\AppData\\Local\\nvs\\node\\8.14.0\\x64\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\Projects\JS\Electron\macro-recorder\node_modules\ref
gyp ERR! node -v v8.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN macro-recorder@1.0.0 No description
npm WARN macro-recorder@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: iconv@2.3.3 (node_modules\iconv):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: iconv@2.3.3 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ref-napi@1.4.1 (node_modules\ref-napi):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ref-napi@1.4.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ref@1.3.5 (node_modules\ref):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ref@1.3.5 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ active-win@5.0.0
added 3 packages from 3 contributors, updated 1 package and audited 513 packages in 53.907s
found 0 vulnerabilities


E:\Projects\JS\Electron\macro-recorder>
```

First I got an error stating the node gyp was not able to find the python 2.7 so I installed python 2.7 inn c/python27 and then when i tried again i got this error.

**Comment by sindresorhus** [comment]
Duplicate of #38

**Comment by vickylance** [comment]
Lowering the version to node 8.x solved this issue
